[project]
name = "aws-dbt-snowflake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dishantjanii", email = "dishantjaniofficial@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.12.5",
    "dbt-snowflake>=1.12.1",
    "sqlfmt>=0.0.3",
]

[project.scripts]
dbt-snowflake = "dbt_snowflake:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
