aws_dbt_snowflake_project:
  outputs:
    dev:
      account: JCANRHC-BJ19374
      database: AIRBNB
      password: dbtPassword123
      role: TRANSFORM
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: dbt_snow
      warehouse: COMPUTE_WH
  target: dev
my_practice:
  outputs:
    dev:
      account: JCANRHC-BJ19374
      database: ECOM
      password: dbtPassword123
      role: PERSONAL
      schema: RAW
      threads: 1
      type: snowflake
      user: dbt_practice
      warehouse: PRACTICE
  target: dev
netflix:
  outputs:
    dev:
      account: JCANRHC-BJ19374
      database: NETFLIX
      password: dbtPassword123
      role: TRANSFORM
      schema: DEV
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
