aws_dbt_snowflake_project:
  outputs:
    dev:
      account: YOUR_SNOWFLAKE_ACCOUNT       # e.g. abc12345.us-east-1
      database: YOUR_DATABASE               # e.g. AIRBNB
      password: YOUR_PASSWORD
      role: YOUR_ROLE                       # e.g. TRANSFORM
      schema: YOUR_SCHEMA                   # e.g. dbt_schema
      threads: 1
      type: snowflake
      user: YOUR_USERNAME
      warehouse: YOUR_WAREHOUSE             # e.g. COMPUTE_WH
  target: dev
my_practice:
  outputs:
    dev:
      account: YOUR_SNOWFLAKE_ACCOUNT
      database: YOUR_DATABASE
      password: YOUR_PASSWORD
      role: YOUR_ROLE
      schema: YOUR_SCHEMA
      threads: 1
      type: snowflake
      user: YOUR_USERNAME
      warehouse: YOUR_WAREHOUSE
  target: dev
netflix:
  outputs:
    dev:
      account: YOUR_SNOWFLAKE_ACCOUNT
      database: YOUR_DATABASE
      password: YOUR_PASSWORD
      role: YOUR_ROLE
      schema: YOUR_SCHEMA
      threads: 1
      type: snowflake
      user: YOUR_USERNAME
      warehouse: YOUR_WAREHOUSE
  target: dev
